#!/usr/bin/perl -s

BEGIN {
    use File::Basename;
    our $dir = dirname(__FILE__) . "/../../lib";
    unshift @INC, $dir;
}
use FBSite::Layout;

# Split on first <HR> to get linked a href list
($nav, @doc) = split m#<hr[ /]*>#, join '', <STDIN>;

# Get title
$tit = shift;

# Fuck with nav, fuck .sh
if ($selected) {
    $tit =~ s#(<option\s+value="$selected")#$1 selected#;
}

print layout_noads(navbar($tit, $nav), @doc);
